branch-defaults:
  default:
    environment: VirtualDesktop-env
    group_suffix: null
environment-defaults:
  VirtualDesktop-env:
    branch: null
    repository: null
  VirtualDesktop-env-simon:
    branch: null
    repository: null
global:
  application_name: VirtualDesktop
  branch: null
  default_ec2_keyname: null
  default_platform: node.js
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
